Add multi-stage build with Xdebug support.
Enhanced Dockerfile for multi-stage builds, added Xdebug for development, and set up environment configurations for better debugging capabilities. Updated docker-compose files to target development builds and included necessary volume mappings and environment variables.

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,7 +1,15 @@
-FROM php:8.3-fpm-alpine3.20
+FROM php:8.3-fpm-alpine3.20 AS app
 LABEL authors="Melville Spence"
 
-RUN docker-php-ext-install pdo pdo_mysql
+# Useful PHP extension installer image, copy binary into your container
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
+
+# Install php extensions
+# exit on errors, exit on unset variables, print every command as it is executed
+RUN set -eux; \
+    install-php-extensions pdo pdo_mysql;
+
+# RUN docker-php-ext-install pdo pdo_mysql
 
 # allow super user - set this if you use Composer as a
 # super user at all times like in docker containers
@@ -9,7 +17,7 @@ ENV COMPOSER_ALLOW_SUPERUSER=1
 
 # obtain composer using multi-stage build
 # https://docs.docker.com/build/building/multi-stage/
-COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
+COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer
 
 #Here, we are copying only composer.json and composer.lock (instead of copying the entire source)
 # right before doing composer install.
@@ -26,3 +34,20 @@ COPY ./app .
 
 # run composer dump-autoload --optimize
 RUN composer dump-autoload --optimize
+
+# Dev image
+# This stage is meant to be target-built into a separate image
+# https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage
+# https://docs.docker.com/compose/compose-file/#target
+FROM app AS app_dev
+
+# Xdebug has different modes / functionalities. We can default to 'off' and set to 'debug'
+# when we run docker compose up if we need it
+ENV XDEBUG_MODE=off
+
+# Copy xdebug config file into container
+COPY ./php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
+
+# Install xdebug
+RUN set -eux; \
+	install-php-extensions xdebug
